import { Issue } from "@/types";

export const mockIssues: Issue[] = [
  {
    id: "ISS-2024-001",
    title: "Large pothole on Main Road near Bus Stand",
    description: "There is a deep pothole causing traffic issues and accidents. Urgent repair needed.",
    category: "POTHOLES",
    status: "NEW",
    location: {
      address: "Main Road, near Bus Stand",
      ward: "Ward 12",
      city: "Ranchi",
      lat: 23.3441,
      lng: 85.3096,
    },
    reporter: {
      name: "Rajesh Kumar",
      phone: "+91-98XXX-XXXXX",
    },
    images: [
      "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400",
      "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=400",
    ],
    reportedDate: "2024-11-18T09:30:00Z",
    updatedDate: "2024-11-18T09:30:00Z",
    history: [
      {
        timestamp: "2024-11-18T09:30:00Z",
        status: "NEW",
        updatedBy: "System",
        department: "ROADS",
        notes: "Issue reported by citizen",
      },
    ],
    slaBreached: false,
    ageInHours: 48,
  },
  {
    id: "ISS-2024-002",
    title: "Garbage pile near Market Area",
    description: "Uncollected garbage for 5 days. Creating health hazard and bad smell.",
    category: "GARBAGE",
    status: "ACKNOWLEDGED",
    location: {
      address: "Market Road, Sector 5",
      ward: "Ward 8",
      city: "Jamshedpur",
      lat: 22.8046,
      lng: 86.2029,
    },
    reporter: {
      name: "Priya Sharma",
      phone: "+91-97XXX-XXXXX",
    },
    assignedTo: {
      department: "SANITATION",
      officerName: "Amit Singh",
    },
    images: [
      "https://images.unsplash.com/photo-1621451537084-482c73073a0f?w=400",
    ],
    reportedDate: "2024-11-17T14:20:00Z",
    updatedDate: "2024-11-18T10:15:00Z",
    history: [
      {
        timestamp: "2024-11-17T14:20:00Z",
        status: "NEW",
        updatedBy: "System",
        department: "SANITATION",
        notes: "Issue reported by citizen",
      },
      {
        timestamp: "2024-11-18T10:15:00Z",
        status: "ACKNOWLEDGED",
        updatedBy: "Amit Singh",
        department: "SANITATION",
        notes: "Team will be sent for collection tomorrow",
      },
    ],
    slaBreached: false,
    ageInHours: 67,
  },
  {
    id: "ISS-2024-003",
    title: "Street light not working on Park Street",
    description: "All street lights are off for the past week. Dark area causing safety issues.",
    category: "STREETLIGHTS",
    status: "IN_PROGRESS",
    location: {
      address: "Park Street, Block C",
      ward: "Ward 15",
      city: "Ranchi",
      lat: 23.3629,
      lng: 85.3346,
    },
    reporter: {
      name: "Sunita Devi",
      phone: "+91-99XXX-XXXXX",
    },
    assignedTo: {
      department: "ELECTRICITY",
      officerName: "Manoj Yadav",
    },
    images: [
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
    ],
    reportedDate: "2024-11-15T18:45:00Z",
    updatedDate: "2024-11-19T09:00:00Z",
    history: [
      {
        timestamp: "2024-11-15T18:45:00Z",
        status: "NEW",
        updatedBy: "System",
        department: "ELECTRICITY",
        notes: "Issue reported by citizen",
      },
      {
        timestamp: "2024-11-16T11:00:00Z",
        status: "ACKNOWLEDGED",
        updatedBy: "Manoj Yadav",
        department: "ELECTRICITY",
        notes: "Inspection scheduled",
      },
      {
        timestamp: "2024-11-19T09:00:00Z",
        status: "IN_PROGRESS",
        updatedBy: "Manoj Yadav",
        department: "ELECTRICITY",
        notes: "Electrician team on site. Replacing faulty wiring.",
      },
    ],
    slaBreached: true,
    ageInHours: 110,
  },
  {
    id: "ISS-2024-004",
    title: "Water pipe leakage causing road damage",
    description: "Underground water pipe leaking heavily. Water wastage and road getting damaged.",
    category: "WATER",
    status: "RESOLVED",
    location: {
      address: "MG Road, near School",
      ward: "Ward 3",
      city: "Dhanbad",
      lat: 23.7957,
      lng: 86.4304,
    },
    reporter: {
      name: "Vikash Tiwari",
      phone: "+91-96XXX-XXXXX",
    },
    assignedTo: {
      department: "WATER",
      officerName: "Ravi Mishra",
    },
    images: [
      "https://images.unsplash.com/photo-1581092918484-8313e1e00e15?w=400",
      "https://images.unsplash.com/photo-1581092162384-8987c1d64718?w=400",
    ],
    reportedDate: "2024-11-10T08:15:00Z",
    updatedDate: "2024-11-14T16:30:00Z",
    history: [
      {
        timestamp: "2024-11-10T08:15:00Z",
        status: "NEW",
        updatedBy: "System",
        department: "WATER",
        notes: "Issue reported by citizen",
      },
      {
        timestamp: "2024-11-10T14:00:00Z",
        status: "ACKNOWLEDGED",
        updatedBy: "Ravi Mishra",
        department: "WATER",
        notes: "Emergency repair team dispatched",
      },
      {
        timestamp: "2024-11-11T10:00:00Z",
        status: "IN_PROGRESS",
        updatedBy: "Ravi Mishra",
        department: "WATER",
        notes: "Pipe repair work started",
      },
      {
        timestamp: "2024-11-14T16:30:00Z",
        status: "RESOLVED",
        updatedBy: "Ravi Mishra",
        department: "WATER",
        notes: "Pipe replaced. Road repaired. Issue resolved.",
      },
    ],
    slaBreached: false,
    ageInHours: 248,
  },
  {
    id: "ISS-2024-005",
    title: "Sewage overflow in residential area",
    description: "Blocked sewage line causing overflow in streets. Health emergency.",
    category: "SEWAGE",
    status: "ACKNOWLEDGED",
    location: {
      address: "Housing Colony, Sector 9",
      ward: "Ward 20",
      city: "Ranchi",
      lat: 23.3725,
      lng: 85.3235,
    },
    reporter: {
      name: "Anita Kumari",
      phone: "+91-94XXX-XXXXX",
    },
    assignedTo: {
      department: "SANITATION",
      officerName: "Santosh Kumar",
    },
    images: [
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400",
    ],
    reportedDate: "2024-11-19T07:00:00Z",
    updatedDate: "2024-11-19T12:30:00Z",
    history: [
      {
        timestamp: "2024-11-19T07:00:00Z",
        status: "NEW",
        updatedBy: "System",
        department: "SANITATION",
        notes: "Issue reported by citizen",
      },
      {
        timestamp: "2024-11-19T12:30:00Z",
        status: "ACKNOWLEDGED",
        updatedBy: "Santosh Kumar",
        department: "SANITATION",
        notes: "Team with equipment being arranged",
      },
    ],
    slaBreached: false,
    ageInHours: 18,
  },
  {
    id: "ISS-2024-006",
    title: "Multiple potholes on Highway stretch",
    description: "Several potholes on 2km highway stretch causing vehicle damage",
    category: "POTHOLES",
    status: "IN_PROGRESS",
    location: {
      address: "NH-33, near Toll Plaza",
      ward: "Ward 25",
      city: "Jamshedpur",
      lat: 22.7925,
      lng: 86.1842,
    },
    reporter: {
      name: "Deepak Singh",
      phone: "+91-98XXX-XXXXX",
    },
    assignedTo: {
      department: "ROADS",
      officerName: "Ajay Verma",
    },
    images: [
      "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400",
    ],
    reportedDate: "2024-11-16T11:20:00Z",
    updatedDate: "2024-11-19T08:45:00Z",
    history: [
      {
        timestamp: "2024-11-16T11:20:00Z",
        status: "NEW",
        updatedBy: "System",
        department: "ROADS",
        notes: "Issue reported by citizen",
      },
      {
        timestamp: "2024-11-17T09:00:00Z",
        status: "ACKNOWLEDGED",
        updatedBy: "Ajay Verma",
        department: "ROADS",
        notes: "Site inspection completed",
      },
      {
        timestamp: "2024-11-19T08:45:00Z",
        status: "IN_PROGRESS",
        updatedBy: "Ajay Verma",
        department: "ROADS",
        notes: "Road repair work started",
      },
    ],
    slaBreached: false,
    ageInHours: 74,
  },
  {
    id: "ISS-2024-007",
    title: "Stray dogs near school causing safety issues",
    description: "Pack of stray dogs near school entrance. Children scared to enter.",
    category: "OTHER",
    status: "REJECTED",
    location: {
      address: "Government School, Block A",
      ward: "Ward 10",
      city: "Ranchi",
      lat: 23.3551,
      lng: 85.3150,
    },
    reporter: {
      name: "Meena Singh",
      phone: "+91-91XXX-XXXXX",
    },
    assignedTo: {
      department: "OTHER",
      officerName: "Prakash Jha",
    },
    images: [],
    reportedDate: "2024-11-12T08:30:00Z",
    updatedDate: "2024-11-13T15:00:00Z",
    history: [
      {
        timestamp: "2024-11-12T08:30:00Z",
        status: "NEW",
        updatedBy: "System",
        department: "OTHER",
        notes: "Issue reported by citizen",
      },
      {
        timestamp: "2024-11-13T10:00:00Z",
        status: "ACKNOWLEDGED",
        updatedBy: "Prakash Jha",
        department: "OTHER",
        notes: "Contacted animal welfare department",
      },
      {
        timestamp: "2024-11-13T15:00:00Z",
        status: "REJECTED",
        updatedBy: "Prakash Jha",
        department: "OTHER",
        notes: "Not under municipal authority jurisdiction. Redirected to Animal Welfare Board.",
      },
    ],
    slaBreached: false,
    ageInHours: 176,
  },
  {
    id: "ISS-2024-008",
    title: "No water supply for 3 days",
    description: "Entire area without water supply. Facing severe crisis.",
    category: "WATER",
    status: "IN_PROGRESS",
    location: {
      address: "Satellite Town, Phase 2",
      ward: "Ward 18",
      city: "Dhanbad",
      lat: 23.8103,
      lng: 86.4402,
    },
    reporter: {
      name: "Ramesh Gupta",
      phone: "+91-93XXX-XXXXX",
    },
    assignedTo: {
      department: "WATER",
      officerName: "Suresh Pandey",
    },
    images: [],
    reportedDate: "2024-11-17T06:00:00Z",
    updatedDate: "2024-11-19T14:00:00Z",
    history: [
      {
        timestamp: "2024-11-17T06:00:00Z",
        status: "NEW",
        updatedBy: "System",
        department: "WATER",
        notes: "Issue reported by citizen",
      },
      {
        timestamp: "2024-11-17T10:30:00Z",
        status: "ACKNOWLEDGED",
        updatedBy: "Suresh Pandey",
        department: "WATER",
        notes: "Pump failure identified. Ordering replacement parts.",
      },
      {
        timestamp: "2024-11-19T14:00:00Z",
        status: "IN_PROGRESS",
        updatedBy: "Suresh Pandey",
        department: "WATER",
        notes: "New pump installed. Testing water flow.",
      },
    ],
    slaBreached: true,
    ageInHours: 82,
  },
];
